# emo_tune_api\render.yaml

services:
  - type: web
    name: emotune-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
    healthCheckPath: /health
